import hashlib
import uuid
import datetime
import discord
from models.incident import Incident, IncidentSeverity, IncidentStatus
from models.rules import ThreatEvaluation
from repositories.incident_repository import incident_repo
from utils.logger import security_logger

class IncidentService:
    """Manages the creation, triage, and resolution of security incidents."""

    async def register_incident(
        self,
        guild: discord.Guild,
        member: discord.Member,
        channel: discord.TextChannel,
        evaluation: ThreatEvaluation,
        raw_content: str,
        action_taken: str
    ) -> Incident:
        today_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d")
        rand_id = uuid.uuid4().hex[:6].upper()
        incident_id = f"INC-{today_str}-{rand_id}"
        correlation_id = f"CORR-{hashlib.sha256(f'{guild.id}-{member.id}-{today_str}'.encode()).hexdigest()[:12]}"

        # Map threat score to IncidentSeverity
        if evaluation.score >= 75:
            severity = IncidentSeverity.CRITICAL
        elif evaluation.score >= 50:
            severity = IncidentSeverity.HIGH
        elif evaluation.score >= 25:
            severity = IncidentSeverity.MEDIUM
        else:
            severity = IncidentSeverity.LOW

        evidence = {
            "raw_content": raw_content,
            "content_hash": hashlib.sha256(raw_content.encode()).hexdigest(),
            "channel_id": channel.id,
            "channel_name": channel.name,
            "join_delta": evaluation.join_delta,
            "account_age": evaluation.account_age,
            "entropy": evaluation.entropy,
            "flags": evaluation.flags,
            "action_executed": action_taken,
            "user_avatar": member.display_avatar.url
        }

        incident = Incident(
            incident_id=incident_id,
            guild_id=guild.id,
            user_id=member.id,
            user_name=str(member),
            severity=severity,
            status=IncidentStatus.OPEN,
            title=f"{evaluation.verdict} in #{channel.name}",
            summary=f"User {member.mention} ({member.id}) scored {evaluation.score}/100. Action: {action_taken.upper()}.",
            risk_score=evaluation.score,
            correlation_id=correlation_id,
            evidence=evidence,
            notes=[f"Auto-generated by ThreatEngine. Verdict: {evaluation.verdict}"]
        )

        await incident_repo.create_incident(incident)

        security_logger.log_event(
            event_type="INCIDENT_CREATED",
            guild_id=guild.id,
            user_id=member.id,
            correlation_id=correlation_id,
            severity=severity.value,
            details=evidence
        )

        return incident

incident_service = IncidentService()